name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: build-and-test
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          include-prerelease: false
          
      - name: Client Build
        run: dotnet publish ./Client/Client.csproj --output ./dist/lient

      - name: Api Build
        run: dotnet publish ./Api/Api.csproj --output ./dist/api

      - name: Set the SWA environment
        id: swa-env
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "ENVIRONMENT=production">> $GITHUB_OUTPUT
          else
            echo "ENVIRONMENT=staging${{ github.event.number }}">> $GITHUB_OUTPUT
          fi

      - name: Install Node
        uses: actions/setup-node@v3
      - name: Deploy Artifacts to SWA
        run: |
          npm install -g @azure/static-web-apps-cli@1.1.1
          swa deploy -a dist/client -i dist/api --deployment-token ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_MUD_05C473C03 }} --env ${{ steps.swa-env.outputs.ENVIRONMENT }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_MUD_05C473C03 }}
          action: "close"
